import { Analytics } from '@vercel/analytics/react';
import { ClerkProvider } from '@clerk/nextjs';
import StyledComponentsRegistry from '@/theme/StyledComponentsRegistry';
import ReduxProvider from '@/store/ReduxProvider';
import InitializeApp from '@/components/InitializeApp';
import '@/i18n/client';
import 'antd/dist/reset.css';
import { FC, PropsWithChildren } from 'react';
import postsService from '@/services/postsService';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: FC<PropsWithChildren> = async ({ children }) => {
  const posts = await postsService.getPosts();
  console.log(posts);
  return (
    <ClerkProvider>
      <StyledComponentsRegistry>
        <html lang="en-US">
          <Analytics />
          <body>
            <ReduxProvider>
              <InitializeApp>{children}</InitializeApp>
            </ReduxProvider>
          </body>
        </html>
      </StyledComponentsRegistry>
    </ClerkProvider>
  );
};

export default RootLayout;
