name: Pull Request

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'
    - name: Set env to dev
      shell: bash
      run: |
        touch .env
    - name: Install Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
